#lang racket
(require "File_handle.rkt")
(require "Database_handle.rkt")
(define pro-save (new database-class))
(send pro-save create-new-item 1)
(send pro-save create-new-item 2)
(send pro-save create-new-item 3)
(send pro-save set-item-name! 1 "Oppigards") 
(send pro-save set-item-name! 2 "Mellerud") 
(send pro-save set-item-name! 3 "Bitburger") 
(send pro-save set-item-price! 1 1500)
(send pro-save set-item-price! 2 3000)
(send pro-save set-item-price! 3 2500)
(send pro-save add-item-stock 1 100)
(send pro-save add-item-stock 2 100)
(send pro-save add-item-stock 3 100)
(send pro-save set-item-for-sale! 1 #t)
(send pro-save get-item-name 1)
;(send pro-save get-item-name 2)
;(send pro-save get-item-name 3)
(send pro-save get-item-price 1)
;(send pro-save get-item-price 2)
;(send pro-save get-item-price 3)
(create-database-file "working.database" pro-save)
(define after-save (read-database-file "working.database" (new database-class)))
(send after-save get-item-name 1)
(send after-save get-item-name 2)
(send after-save get-item-name 3)
(send after-save get-item-price 1)
(send after-save get-item-price 2)
(send after-save get-item-price 3)
(send after-save get-item-stock 1)
(send after-save get-item-stock 2)
(send after-save get-item-stock 3)